// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTsk4WLPsGa-ub2ub9BMJ46EUORVW7Nak',
    appId: '1:371420354091:web:1d99f1e9058e68cf03fc6e',
    messagingSenderId: '371420354091',
    projectId: 'todo-app-6b6b2',
    authDomain: 'todo-app-6b6b2.firebaseapp.com',
    storageBucket: 'todo-app-6b6b2.appspot.com',
    measurementId: 'G-B3SPK96W2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8jZoiXWFxsNiIe1HEocA7Az8URBf5fOI',
    appId: '1:371420354091:android:3fae99780132849203fc6e',
    messagingSenderId: '371420354091',
    projectId: 'todo-app-6b6b2',
    storageBucket: 'todo-app-6b6b2.appspot.com',
  );

  

  

  
}
